version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - "master"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b7:35:a6:4e:9b:0d:6d:d4:78:1e:9a:97:2a:66:6b:be"
      - checkout
      - restore_cache:
          keys:
            - imooc
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: imooc
      - run:
          name: build
          command: npm build
      - run:
          name: prepare shell commands
          # shell chmod +x
          command: chmod +x script/deploy.sh
      - run:
          name: run deploy
          command: ./script/deploy.sh